CREATE TABLE IF NOT EXISTS users
(
  user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name     VARCHAR NOT NULL,
  email    VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requests
(
  request_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description  VARCHAR NOT NULL,
  requestor_id BIGINT  NOT NULL REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS items
(
  item_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR NOT NULL,
  description  VARCHAR NOT NULL,
  is_available BOOLEAN NOT NULL DEFAULT FALSE,
  owner_id     BIGINT  NOT NULL REFERENCES users (user_id),
  request_id   BIGINT           REFERENCES requests (request_id)
);

CREATE TABLE IF NOT EXISTS bookings
(
  booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_date  TIMESTAMP WITHOUT TIME ZONE     NOT NULL,
  finish_date TIMESTAMP WITHOUT TIME ZONE     NOT NULL,
  item_id     BIGINT                          NOT NULL REFERENCES items (item_id),
  booker_id   BIGINT                          NOT NULL REFERENCES users (user_id),
  owner_id    BIGINT                          NOT NULL REFERENCES users (user_id),
  status      VARCHAR                         NOT NULL,
  CONSTRAINT  finish_after_start CHECK (finish_date > start_date)
);

CREATE TABLE IF NOT EXISTS comments
(
  comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text       VARCHAR NOT NULL,
  item_id    BIGINT  NOT NULL REFERENCES items (item_id),
  author_id  BIGINT  NOT NULL REFERENCES users (user_id)
);

